import type { LucideIcon } from "lucide-react";
import { Sparkles, Users } from "lucide-react";

export type MemberSocial = {
  title: string;
  url: string;
};

export type Member = {
  id: string;
  name: string;
  nickname: string;
  img: string;
  url: string;
  team: string;
  generationId: string;
  generationLabel: string;
  isGraduate: boolean;
  socials: MemberSocial[];
};

/** Full JKT48 member roster, grouped by generation. */
export const members: Member[] = [
  {
    id: "1",
    name: "Abigail Rachel",
    nickname: "Aralie",
    img: "https://images.jkt48connect.com/jkt48/members/fdd05228ebdb4ed65041.jpg",
    url: "aralie",
    team: "passion",
    generationId: "gen12",
    generationLabel: "Generation 12",
    isGraduate: false,
    socials: [{ title: "X", url: "https://twitter.com/Aralie_JKT48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48.aralie/" }, { title: "TikTok", url: "https://www.tiktok.com/@jkt48.aralie/" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Aralie" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/f001ba66-3c51-4849-9afa-13cf74eb1571&af_web_dp=https://www.idn.app/jkt48_aralie" }],
  },
  {
    id: "2",
    name: "Adeline Wijaya",
    nickname: "Delynn",
    img: "https://images.jkt48connect.com/jkt48/members/794f7ece1ae70afdb8a4.jpg",
    url: "delynn",
    team: "dream",
    generationId: "gen12",
    generationLabel: "Generation 12",
    isGraduate: false,
    socials: [{ title: "X", url: "https://twitter.com/Delynn_JKT48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48.delynn/" }, { title: "TikTok", url: "https://www.tiktok.com/@jkt48.delynn/" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Delynn" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/266ef38a-da00-4d13-ba77-f94da68599ee&af_web_dp=https://www.idn.app/jkt48_delynn" }],
  },
  {
    id: "6",
    name: "Afera Thalia",
    nickname: "Fera",
    img: "https://images.jkt48connect.com/jkt48/members/2d7cfdccd87e56c49323.jpg",
    url: "fera",
    team: "trainee",
    generationId: "gen14",
    generationLabel: "Generation 14",
    isGraduate: false,
    socials: [],
  },
  {
    id: "13",
    name: "Alya Amanda",
    nickname: "Alya",
    img: "https://images.jkt48connect.com/jkt48/members/1e448c3c22923fbcbbf5.jpg",
    url: "alya",
    team: "love",
    generationId: "gen11",
    generationLabel: "Generation 11",
    isGraduate: false,
    socials: [{ title: "Twitter", url: "https://twitter.com/AA_AlyaJKT48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48.alya_/" }, { title: "TikTok", url: "https://www.tiktok.com/@alyajkt48/" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Alya" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/74e76417-0353-487f-b9b7-7520c0398e87&af_web_dp=https://www.idn.app/jkt48_alya" }],
  },
  {
    id: "22",
    name: "Angelina Christy",
    nickname: "Christy",
    img: "https://images.jkt48connect.com/jkt48/members/1b876ed8c5d1e2fc2c95.jpg",
    url: "christy",
    team: "passion",
    generationId: "gen7",
    generationLabel: "Generation 7",
    isGraduate: false,
    socials: [{ title: "Instagram", url: "https://instagram.com/jkt48.christy" }, { title: "Twitter", url: "https://twitter.com/A_ChristyJKT48" }, { title: "TikTok", url: "https://www.tiktok.com/@christyjkt48" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Christy" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/01506e57-d837-4a1e-8dd4-3e99e3489ac8&af_web_dp=https://www.idn.app/jkt48_christy" }],
  },
  {
    id: "26",
    name: "Anindya Ramadhani",
    nickname: "Anindya",
    img: "https://images.jkt48connect.com/jkt48/members/0ded999ff2368fda81c4.jpg",
    url: "anindya",
    team: "love",
    generationId: "gen11",
    generationLabel: "Generation 11",
    isGraduate: false,
    socials: [{ title: "Twitter", url: "https://twitter.com/AR_AnindyaJKT48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48.anindya_/" }, { title: "TikTok", url: "https://www.tiktok.com/@anindyajkt48/" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Anindya" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/a5c72141-65a3-47be-86ef-1dc1feaab10d&af_web_dp=https://www.idn.app/jkt48_anindya" }],
  },
  {
    id: "28",
    name: "Astrella Virgiananda",
    nickname: "Virgi",
    img: "https://images.jkt48connect.com/jkt48/members/26614475cffb3a73d98c.jpg",
    url: "virgi",
    team: "trainee",
    generationId: "gen13",
    generationLabel: "Generation 13",
    isGraduate: false,
    socials: [{ title: "X", url: "https://twitter.com/A_VirgiJKT48" }, { title: "Instagram", url: "https://instagram.com/virgi.jkt48" }, { title: "TikTok", url: "https://www.tiktok.com/@jkt48.virgi" }],
  },
  {
    id: "30",
    name: "Aulia Riza",
    nickname: "Auwia",
    img: "https://images.jkt48connect.com/jkt48/members/fcd2dba9f22f6525be7b.jpg",
    url: "auwia",
    team: "trainee",
    generationId: "gen13",
    generationLabel: "Generation 13",
    isGraduate: false,
    socials: [{ title: "X", url: "https://twitter.com/Auwia_JKT48" }, { title: "Instagram", url: "https://instagram.com/auwia.jkt48" }, { title: "TikTok", url: "https://www.tiktok.com/@jkt48.auwia" }],
  },
  {
    id: "31",
    name: "Aurellia",
    nickname: "Lia",
    img: "https://images.jkt48connect.com/jkt48/members/171fe658ba6561cbbc7d.jpg",
    url: "lia",
    team: "love",
    generationId: "gen10",
    generationLabel: "Generation 10",
    isGraduate: false,
    socials: [{ title: "Twitter", url: "https://twitter.com/AU_LiaJKT48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48.aurellia_/" }, { title: "TikTok", url: "https://tiktok.com/@jkt48.aurellia_" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Lia" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/15dfee86-a928-4a15-8c90-6aa21097d0ff&af_web_dp=https://www.idn.app/jkt48_lia" }],
  },
  {
    id: "33",
    name: "Aurhel Alana",
    nickname: "Lana",
    img: "https://images.jkt48connect.com/jkt48/members/3f5586e7f5eea4f3a5e2.jpg",
    url: "lana",
    team: "love",
    generationId: "gen12",
    generationLabel: "Generation 12",
    isGraduate: false,
    socials: [{ title: "X", url: "https://twitter.com/AR_LanaJKT48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48.lana.a/" }, { title: "TikTok", url: "https://www.tiktok.com/@jkt48.lana/" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Lana" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/e2af7271-2598-4ee8-8760-68043e671e6d&af_web_dp=https://www.idn.app/jkt48_lana" }],
  },
  {
    id: "39",
    name: "Bong Aprilli",
    nickname: "Rilly",
    img: "https://images.jkt48connect.com/jkt48/members/243fead37df5610d3e73.jpg",
    url: "rilly",
    team: "trainee",
    generationId: "gen13",
    generationLabel: "Generation 13",
    isGraduate: false,
    socials: [{ title: "X", url: "https://twitter.com/Rilly_JKT48" }, { title: "Instagram", url: "https://instagram.com/rilly.jkt48_" }, { title: "TikTok", url: "https://www.tiktok.com/@jkt48.rilly" }],
  },
  {
    id: "43",
    name: "Carissa Dini",
    nickname: "Carissa",
    img: "https://images.jkt48connect.com/jkt48/members/28a096699345f672c345.jpg",
    url: "carissa",
    team: "trainee",
    generationId: "gen14",
    generationLabel: "Generation 14",
    isGraduate: false,
    socials: [],
  },
  {
    id: "44",
    name: "Catherina Vallencia",
    nickname: "Erine",
    img: "https://images.jkt48connect.com/jkt48/members/548009752de2126bfe2c.jpg",
    url: "erine",
    team: "passion",
    generationId: "gen12",
    generationLabel: "Generation 12",
    isGraduate: false,
    socials: [{ title: "X", url: "https://twitter.com/CErine_JKT48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48.erine/" }, { title: "TikTok", url: "https://www.tiktok.com/@jkt48.erine_/" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Erine" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/b0e628c8-0b0a-40c7-aa6a-a1c7660c25ce&af_web_dp=https://www.idn.app/jkt48_erine" }],
  },
  {
    id: "45",
    name: "Cathleen Nixie",
    nickname: "Cathy",
    img: "https://images.jkt48connect.com/jkt48/members/88413a7f463449b1cdb5.jpg",
    url: "cathy",
    team: "love",
    generationId: "gen11",
    generationLabel: "Generation 11",
    isGraduate: false,
    socials: [{ title: "Twitter", url: "https://twitter.com/N_CathyJKT48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48.cathy/" }, { title: "TikTok", url: "https://www.tiktok.com/@cathyjkt48/" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Cathy" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/f740e9da-772f-4ae2-8ddd-49f717aacf63&af_web_dp=https://www.idn.app/jkt48_cathy" }],
  },
  {
    id: "46",
    name: "Celline Thefani",
    nickname: "Elin",
    img: "https://images.jkt48connect.com/jkt48/members/dcb15e30cdc7f0a28027.jpg",
    url: "elin",
    team: "love",
    generationId: "gen11",
    generationLabel: "Generation 11",
    isGraduate: false,
    socials: [{ title: "Twitter", url: "https://twitter.com/Elin_JKT48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48.elin_/" }, { title: "TikTok", url: "https://www.tiktok.com/@elinjkt48/" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Elin" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/e0ececb4-71d8-4f32-a221-ef21634a746a&af_web_dp=https://www.idn.app/jkt48_elin" }],
  },
  {
    id: "52",
    name: "Christabella Bonita",
    nickname: "Bella",
    img: "https://images.jkt48connect.com/jkt48/members/4a72b24328ece273ed4c.jpg",
    url: "bella",
    team: "trainee",
    generationId: "gen14",
    generationLabel: "Generation 14",
    isGraduate: false,
    socials: [],
  },
  {
    id: "59",
    name: "Cornelia Vanisa",
    nickname: "Oniel",
    img: "https://images.jkt48connect.com/jkt48/members/0de863b15b32a3028264.jpg",
    url: "oniel",
    team: "passion",
    generationId: "gen8",
    generationLabel: "Generation 8",
    isGraduate: false,
    socials: [{ title: "Twitter", url: "https://twitter.com/C_OnielJKT48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48.oniel/" }, { title: "TikTok", url: "https://www.tiktok.com/@onieljkt48" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Oniel" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/0078fe3c-8f4d-495b-bb7c-bdb2b98d0598&af_web_dp=https://www.idn.app/jkt48_oniel" }],
  },
  {
    id: "60",
    name: "Cynthia Yaputera",
    nickname: "Cynthia",
    img: "https://images.jkt48connect.com/jkt48/members/8c73421cf987944c6cc9.jpg",
    url: "cynthia",
    team: "love",
    generationId: "gen11",
    generationLabel: "Generation 11",
    isGraduate: false,
    socials: [{ title: "Twitter", url: "https://twitter.com/Y_CynthiaJKT48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48.cynthia/" }, { title: "TikTok", url: "https://www.tiktok.com/@cynthiajkt48/" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Cynthia" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/4f795073-38c9-4df7-9388-74b83de69801&af_web_dp=https://www.idn.app/jkt48_cynthia" }],
  },
  {
    id: "64",
    name: "Dena Natalia",
    nickname: "Danella",
    img: "https://images.jkt48connect.com/jkt48/members/2ae55a3e5b386d306a7b.jpg",
    url: "danella",
    team: "passion",
    generationId: "gen11",
    generationLabel: "Generation 11",
    isGraduate: false,
    socials: [{ title: "Twitter", url: "https://twitter.com/Danella_JKT48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48.danella/" }, { title: "TikTok", url: "https://www.tiktok.com/@danellajkt48/" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Danella" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/33139b05-1c43-4b48-bba3-ec960b18b36e&af_web_dp=https://www.idn.app/jkt48_danella" }],
  },
  {
    id: "67",
    name: "Desy Natalia",
    nickname: "Daisy",
    img: "https://images.jkt48connect.com/jkt48/members/0eb9e3bfae38182207f5.jpg",
    url: "daisy",
    team: "passion",
    generationId: "gen11",
    generationLabel: "Generation 11",
    isGraduate: false,
    socials: [{ title: "Twitter", url: "https://twitter.com/Daisy_JKT48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48.daisy/" }, { title: "TikTok", url: "https://www.tiktok.com/@daisyjkt48/" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Daisy" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/b11b0692-d0b8-464c-849a-9e81439a048c&af_web_dp=https://www.idn.app/jkt48_daisy" }],
  },
  {
    id: "82",
    name: "Fahira Putri",
    nickname: "Fahira",
    img: "https://images.jkt48connect.com/jkt48/members/7c45c02bb69ccb9fbdf4.jpg",
    url: "fahira",
    team: "TRAINEE",
    generationId: "trainee",
    generationLabel: "Trainee",
    isGraduate: false,
    socials: [],
  },
  {
    id: "85",
    name: "Fatimah Azzahra",
    nickname: "Rara",
    img: "https://images.jkt48connect.com/jkt48/members/18fcea5914e315cabac8.jpg",
    url: "rara",
    team: "TRAINEE",
    generationId: "trainee",
    generationLabel: "Trainee",
    isGraduate: false,
    socials: [],
  },
  {
    id: "88",
    name: "Febriola Sinambela",
    nickname: "Olla",
    img: "https://images.jkt48connect.com/jkt48/members/c375f1beb2b9b71e6081.jpg",
    url: "olla",
    team: "dream",
    generationId: "gen7",
    generationLabel: "Generation 7",
    isGraduate: false,
    socials: [{ title: "Twitter", url: "https://twitter.com/f_ollajkt48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48.olla" }, { title: "TikTok", url: "https://www.tiktok.com/@ollajkt48" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Olla" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/9c32c2bc-f74e-4420-8be8-f4ac863b8064&af_web_dp=https://www.idn.app/jkt48_olla" }],
  },
  {
    id: "89",
    name: "Feni Fitriyanti",
    nickname: "Feni",
    img: "https://images.jkt48connect.com/jkt48/members/d005e82008e4b7ffcdd5.jpg",
    url: "feni",
    team: "passion",
    generationId: "gen3",
    generationLabel: "Generation 3",
    isGraduate: false,
    socials: [{ title: "Instagram", url: "https://instagram.com/jkt48feni" }, { title: "Twitter", url: "https://twitter.com/F_FeniJKT48/" }, { title: "TikTok", url: "https://www.tiktok.com/@fenijkt48" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Feni" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/13f4d35d-f3a7-482e-a593-91d664c7ffcc&af_web_dp=https://www.idn.app/jkt48_feni" }],
  },
  {
    id: "91",
    name: "Fiony Alveria",
    nickname: "Fiony",
    img: "https://images.jkt48connect.com/jkt48/members/d033c8f3bd1f69836051.jpg",
    url: "fiony",
    team: "love",
    generationId: "gen8",
    generationLabel: "Generation 8",
    isGraduate: false,
    socials: [{ title: "Twitter", url: "https://twitter.com/A_FionyJKT48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48.fiony/" }, { title: "TikTok", url: "https://www.tiktok.com/@fionyjkt48" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Fiony" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/85482779-8b59-4995-a600-f8a4230c29d8&af_web_dp=https://www.idn.app/jkt48_fiony" }],
  },
  {
    id: "94",
    name: "Freya Jayawardana",
    nickname: "Freya",
    img: "https://images.jkt48connect.com/jkt48/members/66a316636ba3ec30d9b4.jpg",
    url: "freya",
    team: "dream",
    generationId: "gen7",
    generationLabel: "Generation 7",
    isGraduate: false,
    socials: [{ title: "Instagram", url: "https://www.instagram.com/jkt48.freya/" }, { title: "Twitter", url: "https://twitter.com/Freya_JKT48" }, { title: "TikTok", url: "https://www.tiktok.com/@freyajkt48" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Freya" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/12addeb8-6ec5-4cea-a3b4-ad86e9bfc8d1&af_web_dp=https://www.idn.app/jkt48_freya" }],
  },
  {
    id: "96",
    name: "Fritzy Rosmerian",
    nickname: "Fritzy",
    img: "https://images.jkt48connect.com/jkt48/members/caa55ca79b3f5dabd44c.jpg",
    url: "fritzy",
    team: "love",
    generationId: "gen12",
    generationLabel: "Generation 12",
    isGraduate: false,
    socials: [{ title: "X", url: "https://twitter.com/RFritzy_JKT48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48.fritzy.r/" }, { title: "TikTok", url: "https://www.tiktok.com/@jkt48.fritzy/" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Fritzy" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/717109e0-a064-4f15-8187-5c4d46e56a58&af_web_dp=https://www.idn.app/jkt48_fritzy" }],
  },
  {
    id: "97",
    name: "Gabriela Abigail",
    nickname: "Ella",
    img: "https://images.jkt48connect.com/jkt48/members/dbca3b8b517c50d65238.jpg",
    url: "ella",
    team: "dream",
    generationId: "gen10",
    generationLabel: "Generation 10",
    isGraduate: false,
    socials: [{ title: "Twitter", url: "https://twitter.com/AM_EllaJKT48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48.ella.a/" }, { title: "TikTok", url: "https://tiktok.com/@jkt48.ella.a" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Ella" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/b0d1e6c3-d356-4b00-8d00-846e5297693b&af_web_dp=https://www.idn.app/jkt48_ella" }],
  },
  {
    id: "102",
    name: "Gendis Mayrannisa",
    nickname: "Gendis",
    img: "https://images.jkt48connect.com/jkt48/members/d606a2a8e63c386ae19c.jpg",
    url: "gendis",
    team: "dream",
    generationId: "gen11",
    generationLabel: "Generation 11",
    isGraduate: false,
    socials: [{ title: "Twitter", url: "https://twitter.com/Gendis_JKT48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48.gendis/" }, { title: "TikTok", url: "https://www.tiktok.com/@gendisjkt48/" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Gendis" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/ab901d82-db49-488c-8d03-da0082ab70e2&af_web_dp=https://www.idn.app/jkt48_gendis" }],
  },
  {
    id: "104",
    name: "Gita Sekar Andarini",
    nickname: "Gita",
    img: "https://images.jkt48connect.com/jkt48/members/a4bdc309cc8292ab5245.jpg",
    url: "gita",
    team: "dream",
    generationId: "gen6",
    generationLabel: "Generation 6",
    isGraduate: false,
    socials: [{ title: "Instagram", url: "https://www.instagram.com/jkt48gita/" }, { title: "Twitter", url: "https://twitter.com/A_GitaJKT48" }, { title: "TikTok", url: "https://www.tiktok.com/@gitajkt48" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Gita" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/82ffac10-ee56-43d0-ad38-ce432384cfe5&af_web_dp=https://www.idn.app/jkt48_gita" }],
  },
  {
    id: "105",
    name: "Grace Octaviani",
    nickname: "Gracie",
    img: "https://images.jkt48connect.com/jkt48/members/e7d31a3e3a737f33b684.jpg",
    url: "gracie",
    team: "love",
    generationId: "gen11",
    generationLabel: "Generation 11",
    isGraduate: false,
    socials: [{ title: "Twitter", url: "https://twitter.com/Gracie_JKT48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48.gracie/" }, { title: "TikTok", url: "https://www.tiktok.com/@graciejkt48/" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Gracie" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/cae4d972-5f14-4512-9706-37c1802a0541&af_web_dp=https://www.idn.app/jkt48_gracie" }],
  },
  {
    id: "107",
    name: "Greesella Adhalia",
    nickname: "Greesel",
    img: "https://images.jkt48connect.com/jkt48/members/fb1f99852afabfb5f14d.jpg",
    url: "greesel",
    team: "dream",
    generationId: "gen11",
    generationLabel: "Generation 11",
    isGraduate: false,
    socials: [{ title: "Twitter", url: "https://twitter.com/Greesel_JKT48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48.greesel/" }, { title: "TikTok", url: "https://www.tiktok.com/@greeseljkt48/" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Greesel" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/0b6b1a63-a0d6-4f4b-be5a-563a63fe279e&af_web_dp=https://www.idn.app/jkt48_greesel" }],
  },
  {
    id: "108",
    name: "Hagia Sopia",
    nickname: "Giaa",
    img: "https://images.jkt48connect.com/jkt48/members/8f1cab11b7e5ddb6ed05.jpg",
    url: "giaa",
    team: "trainee",
    generationId: "gen13",
    generationLabel: "Generation 13",
    isGraduate: false,
    socials: [{ title: "X", url: "https://twitter.com/Giaa_JKT48" }, { title: "Instagram", url: "https://instagram.com/giaa.jkt48" }, { title: "TikTok", url: "https://www.tiktok.com/@jkt48.giaa" }],
  },
  {
    id: "111",
    name: "Heidi Suyangga",
    nickname: "Heidi",
    img: "https://images.jkt48connect.com/jkt48/members/35dac3176f4904d004be.jpg",
    url: "heidi",
    team: "TRAINEE",
    generationId: "trainee",
    generationLabel: "Trainee",
    isGraduate: false,
    socials: [],
  },
  {
    id: "112",
    name: "Helisma Putri",
    nickname: "Eli",
    img: "https://images.jkt48connect.com/jkt48/members/f5b38ea2cf459e8e570b.jpg",
    url: "eli",
    team: "dream",
    generationId: "gen7",
    generationLabel: "Generation 7",
    isGraduate: false,
    socials: [{ title: "Instagram", url: "https://instagram.com/jkt48.eli" }, { title: "Twitter", url: "https://twitter.com/H_EliJKT48" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Eli" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/1f119aa1-3482-44b6-9f68-2ad41c8d6743&af_web_dp=https://www.idn.app/jkt48_eli" }],
  },
  {
    id: "114",
    name: "Hillary Abigail",
    nickname: "Lily",
    img: "https://images.jkt48connect.com/jkt48/members/4af437e88ff2cef53d31.jpg",
    url: "lily",
    team: "love",
    generationId: "gen12",
    generationLabel: "Generation 12",
    isGraduate: false,
    socials: [{ title: "X", url: "https://twitter.com/Lily_JKT48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48.lily_/" }, { title: "TikTok", url: "https://www.tiktok.com/@jkt48.lily/" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Lily" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/e25cfed0-757c-424a-9b6e-85d4ef5b5192&af_web_dp=https://www.idn.app/jkt48_lily" }],
  },
  {
    id: "115",
    name: "Humaira Ramadhani",
    nickname: "Maira",
    img: "https://images.jkt48connect.com/jkt48/members/70c7b0111c18d9bd38b2.jpg",
    url: "maira",
    team: "trainee",
    generationId: "gen13",
    generationLabel: "Generation 13",
    isGraduate: false,
    socials: [{ title: "X", url: "https://twitter.com/Maira_JKT48" }, { title: "Instagram", url: "https://instagram.com/maira.jkt48" }, { title: "TikTok", url: "https://www.tiktok.com/@jkt48.maira" }],
  },
  {
    id: "116",
    name: "Indah Cahya",
    nickname: "Indah",
    img: "https://images.jkt48connect.com/jkt48/members/88f50a5a2a189addd399.jpg",
    url: "indah",
    team: "love",
    generationId: "gen9",
    generationLabel: "Generation 9",
    isGraduate: false,
    socials: [{ title: "Twitter", url: "https://twitter.com/C_IndahJKT48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48indah_/" }, { title: "TikTok", url: "https://www.tiktok.com/@indahjkt48" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Indah" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/539f5185-1414-416c-b84d-2ad366b6d60a&af_web_dp=https://www.idn.app/jkt48_indah" }],
  },
  {
    id: "119",
    name: "Isha Kirana",
    nickname: "Isha",
    img: "https://images.jkt48connect.com/jkt48/members/4c9fc1c7c8ae38e58a73.png",
    url: "isha",
    team: "JKT48_VIRTUAL",
    generationId: "virtual",
    generationLabel: "JKT48 Virtual",
    isGraduate: false,
    socials: [],
  },
  {
    id: "120",
    name: "Jacqueline Immanuela",
    nickname: "Ekin",
    img: "https://images.jkt48connect.com/jkt48/members/416aad5813da82a223ff.jpg",
    url: "ekin",
    team: "trainee",
    generationId: "gen13",
    generationLabel: "Generation 13",
    isGraduate: false,
    socials: [{ title: "X", url: "https://twitter.com/Ekin_JKT48" }, { title: "Instagram", url: "https://instagram.com/ekin.jkt48" }, { title: "TikTok", url: "https://www.tiktok.com/@jkt48.ekin" }],
  },
  {
    id: "121",
    name: "Jazzlyn Trisha",
    nickname: "Trisha",
    img: "https://images.jkt48connect.com/jkt48/members/f97472a5630e8d88e6d3.jpg",
    url: "trisha",
    team: "love",
    generationId: "gen12",
    generationLabel: "Generation 12",
    isGraduate: false,
    socials: [{ title: "X", url: "https://twitter.com/JTrisha_JKT48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48.trisha/" }, { title: "TikTok", url: "https://www.tiktok.com/@jkt48.trisha/" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Trisha" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/92d66abb-0171-4a2b-a30d-37ad58359248&af_web_dp=https://www.idn.app/jkt48_trisha" }],
  },
  {
    id: "123",
    name: "Jemima Evodie",
    nickname: "Jemima",
    img: "https://images.jkt48connect.com/jkt48/members/8d468883bfe7b2655f78.jpg",
    url: "jemima",
    team: "trainee",
    generationId: "gen13",
    generationLabel: "Generation 13",
    isGraduate: false,
    socials: [{ title: "X", url: "https://twitter.com/JE_JemimaJKT48" }, { title: "Instagram", url: "https://instagram.com/jemima.jkt48" }, { title: "TikTok", url: "https://www.tiktok.com/@jkt48.jemima" }],
  },
  {
    id: "127",
    name: "Jessica Chandra",
    nickname: "Jessi",
    img: "https://images.jkt48connect.com/jkt48/members/7a6b2c505531addd536c.jpg",
    url: "jessi",
    team: "passion",
    generationId: "gen7",
    generationLabel: "Generation 7",
    isGraduate: false,
    socials: [{ title: "Instagram", url: "https://www.instagram.com/jkt48.jessi/" }, { title: "Twitter", url: "https://twitter.com/C_JessiJKT48" }, { title: "TikTok", url: "https://www.tiktok.com/@jessijkt48" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Jessi" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/a9579a29-9203-40c0-9326-9837b8eae6e8&af_web_dp=https://www.idn.app/jkt48_jessi" }],
  },
  {
    id: "131",
    name: "Jesslyn Elly",
    nickname: "Lyn",
    img: "https://images.jkt48connect.com/jkt48/members/852a5ba6056355e9d3e3.jpg",
    url: "lyn",
    team: "DREAM",
    generationId: "trainee",
    generationLabel: "Trainee",
    isGraduate: false,
    socials: [],
  },
  {
    id: "143",
    name: "Kathrina Irene",
    nickname: "Kathrina",
    img: "https://images.jkt48connect.com/jkt48/members/891acb8522b12e06a5dc.jpg",
    url: "kathrina",
    team: "passion",
    generationId: "gen9",
    generationLabel: "Generation 9",
    isGraduate: false,
    socials: [{ title: "Twitter", url: "https://twitter.com/I_KathrinaJKT48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48.kathrina/" }, { title: "TikTok", url: "https://www.tiktok.com/@kathrinjkt48" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Kathrina" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/c3d28bcd-d000-4ccc-a9bf-956853cfa433&af_web_dp=https://www.idn.app/jkt48_kathrina" }],
  },
  {
    id: "148",
    name: "Lulu Salsabila",
    nickname: "Lulu",
    img: "https://images.jkt48connect.com/jkt48/members/9bce74cb9cf47af347bd.jpg",
    url: "lulu",
    team: "passion",
    generationId: "gen8",
    generationLabel: "Generation 8",
    isGraduate: false,
    socials: [{ title: "Twitter", url: "https://twitter.com/A_LuluJKT48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48.lulu/" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Lulu" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/531d1bc0-ee91-475f-9e9d-098127b8d383&af_web_dp=https://www.idn.app/jkt48_lulu" }],
  },
  {
    id: "152",
    name: "Marsha Lenathea",
    nickname: "Marsha",
    img: "https://images.jkt48connect.com/jkt48/members/6514606114e83f8ab076.jpg",
    url: "marsha",
    team: "dream",
    generationId: "gen9",
    generationLabel: "Generation 9",
    isGraduate: false,
    socials: [{ title: "Twitter", url: "https://twitter.com/L_MarshaJKT48" }, { title: "Instagram", url: "http://instagram.com/jkt48.marsha/" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Marsha" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/e27569d2-0d2a-4cd8-a0a6-ca2da28e0a62&af_web_dp=https://www.idn.app/jkt48_marsha" }],
  },
  {
    id: "154",
    name: "Maura Nilambari",
    nickname: "Maura",
    img: "https://images.jkt48connect.com/jkt48/members/e0b267e35df28995067d.png",
    url: "maura",
    team: "JKT48_VIRTUAL",
    generationId: "virtual",
    generationLabel: "JKT48 Virtual",
    isGraduate: false,
    socials: [],
  },
  {
    id: "155",
    name: "Maxine Faye",
    nickname: "Maxine",
    img: "https://images.jkt48connect.com/jkt48/members/1385d1ee5bae179290c9.jpg",
    url: "maxine",
    team: "TRAINEE",
    generationId: "trainee",
    generationLabel: "Trainee",
    isGraduate: false,
    socials: [],
  },
  {
    id: "159",
    name: "Michelle Alexandra",
    nickname: "Michie",
    img: "https://images.jkt48connect.com/jkt48/members/7c7e54c46bd416c23dda.jpg",
    url: "michie",
    team: "love",
    generationId: "gen11",
    generationLabel: "Generation 11",
    isGraduate: false,
    socials: [{ title: "Twitter", url: "https://twitter.com/Michie_JKT48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48.michie_/" }, { title: "TikTok", url: "https://www.tiktok.com/@michiejkt48/" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Michie" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/6970e68a-b488-497a-b793-3a735db5e997&af_web_dp=https://www.idn.app/jkt48_michie" }],
  },
  {
    id: "161",
    name: "Michelle Levia",
    nickname: "Levi",
    img: "https://images.jkt48connect.com/jkt48/members/ae0a8e0cbacc09f131d7.jpg",
    url: "levi",
    team: "passion",
    generationId: "gen12",
    generationLabel: "Generation 12",
    isGraduate: false,
    socials: [{ title: "X", url: "https://twitter.com/Levi_JKT48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48.levi/" }, { title: "TikTok", url: "https://www.tiktok.com/@jkt48.levi/" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Levi" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/35d8f1d5-fd07-4109-9ec5-d202f4baf3c1&af_web_dp=https://www.idn.app/jkt48_levi" }],
  },
  {
    id: "162",
    name: "Mikaela Kusjanto",
    nickname: "Mikaela",
    img: "https://images.jkt48connect.com/jkt48/members/3d7336fe3fcdebb6a733.jpg",
    url: "mikaela",
    team: "trainee",
    generationId: "gen13",
    generationLabel: "Generation 13",
    isGraduate: false,
    socials: [{ title: "X", url: "https://x.com/M_MikaelaJKT48/" }, { title: "Instagram", url: "https://instagram.com/mikaela.jkt48" }, { title: "TikTok", url: "https://www.tiktok.com/@jkt48.mikaela" }],
  },
  {
    id: "166",
    name: "Mutiara Azzahra",
    nickname: "Muthe",
    img: "https://images.jkt48connect.com/jkt48/members/835eccbc25e01cc27283.jpg",
    url: "muthe",
    team: "passion",
    generationId: "gen7",
    generationLabel: "Generation 7",
    isGraduate: false,
    socials: [{ title: "Instagram", url: "https://www.instagram.com/jkt48.muthe_" }, { title: "Twitter", url: "https://twitter.com/A_MutheJKT48" }, { title: "TikTok", url: "https://www.tiktok.com/@muthejkt48" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Muthe" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/9f308a8f-29cb-45c0-9df2-6ffd16bc9298&af_web_dp=https://www.idn.app/jkt48_muthe" }],
  },
  {
    id: "175",
    name: "Nayla Suji",
    nickname: "Nayla",
    img: "https://images.jkt48connect.com/jkt48/members/b2cff8934a73496aeabe.jpg",
    url: "nayla",
    team: "love",
    generationId: "gen12",
    generationLabel: "Generation 12",
    isGraduate: false,
    socials: [{ title: "X", url: "https://twitter.com/SNayla_JKT48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48.nayla.s/" }, { title: "TikTok", url: "https://www.tiktok.com/@jkt48.nayla/" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Nayla" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/e243be19-74b7-435b-8e19-13fc669e0224&af_web_dp=https://www.idn.app/jkt48_nayla" }],
  },
  {
    id: "178",
    name: "Nina Tutachia",
    nickname: "Nachia",
    img: "https://images.jkt48connect.com/jkt48/members/2bac96130be18fabc1d4.jpg",
    url: "nachia",
    team: "dream",
    generationId: "gen12",
    generationLabel: "Generation 12",
    isGraduate: false,
    socials: [{ title: "X", url: "https://twitter.com/Nachia_JKT48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48.nachia.t/" }, { title: "TikTok", url: "https://www.tiktok.com/@jkt48.nachia/" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Nachia" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/21a420b0-dd01-4daa-b185-b9020f8bf69d&af_web_dp=https://www.idn.app/jkt48_nachia" }],
  },
  {
    id: "182",
    name: "Nur Intan",
    nickname: "Intan",
    img: "https://images.jkt48connect.com/jkt48/members/b6888878e56fbc2d4540.jpg",
    url: "intan",
    team: "trainee",
    generationId: "gen13",
    generationLabel: "Generation 13",
    isGraduate: false,
    socials: [{ title: "X", url: "https://twitter.com/N_IntanJKT48" }, { title: "Instagram", url: "https://instagram.com/intan.jkt48" }, { title: "TikTok", url: "https://www.tiktok.com/@jkt48.intan" }],
  },
  {
    id: "185",
    name: "Oline Manuel",
    nickname: "Oline",
    img: "https://images.jkt48connect.com/jkt48/members/1cee8b51fffd6620ac47.jpg",
    url: "oline",
    team: "dream",
    generationId: "gen12",
    generationLabel: "Generation 12",
    isGraduate: false,
    socials: [{ title: "X", url: "https://twitter.com/M_OlineJKT48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48.oline/" }, { title: "TikTok", url: "https://www.tiktok.com/@jkt48.oline/" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_OlineM" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/a2b5d818-475d-44ce-af52-e99526482aaf&af_web_dp=https://www.idn.app/jkt48_oline" }],
  },
  {
    id: "187",
    name: "Pia Meraleo",
    nickname: "Pia",
    img: "https://images.jkt48connect.com/jkt48/members/5429ef0ca4d99a65ebe5.jpg",
    url: "pia",
    team: "JKT48_VIRTUAL",
    generationId: "virtual",
    generationLabel: "JKT48 Virtual",
    isGraduate: false,
    socials: [],
  },
  {
    id: "194",
    name: "Putry Jazyta",
    nickname: "Jazzy",
    img: "https://images.jkt48connect.com/jkt48/members/ef484aeb48a89aa9ce48.jpg",
    url: "jazzy",
    team: "TRAINEE",
    generationId: "trainee",
    generationLabel: "Trainee",
    isGraduate: false,
    socials: [],
  },
  {
    id: "195",
    name: "Raisha Syifa",
    nickname: "Raisha",
    img: "https://images.jkt48connect.com/jkt48/members/04f3d3775231948c8a75.jpg",
    url: "raisha",
    team: "passion",
    generationId: "gen10",
    generationLabel: "Generation 10",
    isGraduate: false,
    socials: [{ title: "Twitter", url: "https://twitter.com/SW_RaishaJKT48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48.raisha.s/" }, { title: "TikTok", url: "https://tiktok.com/@jkt48.raisha.s" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Raisha" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/728d224e-6ccb-43d2-a029-a0147dc7fdee&af_web_dp=https://www.idn.app/jkt48_raisha" }],
  },
  {
    id: "196",
    name: "Ralyne Van Irwan",
    nickname: "Ralyne",
    img: "https://images.jkt48connect.com/jkt48/members/6579e6746e1bf27cbcd3.jpg",
    url: "ralyne",
    team: "TRAINEE",
    generationId: "trainee",
    generationLabel: "Trainee",
    isGraduate: false,
    socials: [],
  },
  {
    id: "204",
    name: "Ribka Budiman",
    nickname: "Ribka",
    img: "https://images.jkt48connect.com/jkt48/members/c07b30bb52daa7f4813f.jpg",
    url: "ribka",
    team: "passion",
    generationId: "gen12",
    generationLabel: "Generation 12",
    isGraduate: false,
    socials: [{ title: "X", url: "https://twitter.com/Ribka_JKT48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48.ribka/" }, { title: "TikTok", url: "https://www.tiktok.com/@jkt48.regie/" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Ribka" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/3cbe26d9-ff3f-4985-bbe1-c4403908124a&af_web_dp=https://www.idn.app/jkt48_ribka" }],
  },
  {
    id: "217",
    name: "Sami Maono",
    nickname: "Sami",
    img: "https://images.jkt48connect.com/jkt48/members/2d113e72cab63ba66201.png",
    url: "sami",
    team: "JKT48_VIRTUAL",
    generationId: "virtual",
    generationLabel: "JKT48 Virtual",
    isGraduate: false,
    socials: [],
  },
  {
    id: "221",
    name: "Shabilqis Naila",
    nickname: "Nala",
    img: "https://images.jkt48connect.com/jkt48/members/4cf5e5a692b3c813e3b9.jpg",
    url: "nala",
    team: "dream",
    generationId: "gen12",
    generationLabel: "Generation 12",
    isGraduate: false,
    socials: [{ title: "X", url: "https://twitter.com/Nala_JKT48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48.nala/" }, { title: "TikTok", url: "https://www.tiktok.com/@jkt48.nala/" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Nala" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/8fc7ad64-f7be-492b-97b6-2dae3378dfe2&af_web_dp=https://www.idn.app/jkt48_nala" }],
  },
  {
    id: "231",
    name: "Sona Kalyana",
    nickname: "Sona",
    img: "https://images.jkt48connect.com/jkt48/members/effe2ab2f04b12a1af5c.jpg",
    url: "sona",
    team: "TRAINEE",
    generationId: "trainee",
    generationLabel: "Trainee",
    isGraduate: false,
    socials: [],
  },
  {
    id: "238",
    name: "Tana Nona",
    nickname: "Tana",
    img: "https://images.jkt48connect.com/jkt48/members/7344f36a9afe9dba9117.jpg",
    url: "tana",
    team: "JKT48_VIRTUAL",
    generationId: "virtual",
    generationLabel: "JKT48 Virtual",
    isGraduate: false,
    socials: [],
  },
  {
    id: "244",
    name: "Victoria Kimberly",
    nickname: "Kimmy",
    img: "https://images.jkt48connect.com/jkt48/members/f461d8683026f3ef7e0c.jpg",
    url: "kimmy",
    team: "passion",
    generationId: "gen12",
    generationLabel: "Generation 12",
    isGraduate: false,
    socials: [{ title: "X", url: "https://twitter.com/Kimmy_JKT48" }, { title: "Instagram", url: "https://www.instagram.com/jkt48.kimmy/" }, { title: "TikTok", url: "https://www.tiktok.com/@jkt48.kimmy/" }, { title: "SHOWROOM", url: "https://www.showroom-live.com/JKT48_Kimmy" }, { title: "IDN", url: "https://click.idn.media/VKUf?af_dp=idnapp://profile/52c5c190-3611-4def-866f-76c32c0b837e&af_web_dp=https://www.idn.app/jkt48_kimmy" }],
  },
];

export type GenerationItem = {
  id: string;
  title: string;
  label: string;
  icon: LucideIcon;
  isActive: boolean;
  members: Member[];
};

const GENERATION_ORDER = [
  "gen3",
  "gen6",
  "gen7",
  "gen8",
  "gen9",
  "gen10",
  "gen11",
  "gen12",
  "gen13",
  "gen14",
  "virtual",
  "trainee",
];

/** Sidebar groups derived directly from `members` — counts always match the roster. */
export const generationItems: GenerationItem[] = GENERATION_ORDER.map((genId) => {
  const genMembers = members.filter((m) => m.generationId === genId);
  return {
    id: genId,
    title: genMembers[0]?.generationLabel ?? genId,
    label: String(genMembers.length),
    icon: genId === "trainee" || genId === "virtual" ? Sparkles : Users,
    isActive: false,
    members: genMembers,
  };
}).filter((g) => g.members.length > 0);

export const currentUser = {
  name: "Valzyy",
  email: "valzyy@jkt48connect.com",
};

/* -------------------------------------------------------------------------- */
/*  Chat / Inbox types — used by Chat, ChatConversationList, ChatThread,      */
/*  and ChatProfileDetails components.                                        */
/* -------------------------------------------------------------------------- */

export type Contact = {
  id: string;
  name: string;
  role: string;
  email: string;
  phone: string;
  website: string;
  company: string;
  status: string;
  qualifiedAt: string;
  timezone: string;
  location: string;
  tags: string[];
  generationId: string;
  avatarUrl: string;
};


/* -------------------------------------------------------------------------- */
/*  Synthetic conversation data, generated from the member roster.            */
/*  Represents fan PM purchase threads inside JKT48Connect (per member).      */
/* -------------------------------------------------------------------------- */



/** Bangun Contact langsung dari roster member — tidak lagi bergantung pada data chat sintetis. */
export function buildContactFromMember(member: Member): Contact {
  return {
    id: member.id,
    name: member.nickname,
    role: `JKT48 ${member.generationLabel}`,
    email: `${member.url}@jkt48connect.com`,
    phone: "—",
    website: `jkt48connect.com/member/${member.url}`,
    company: "JKT48Connect",
    status: member.isGraduate ? "Graduated" : "Active member",
    qualifiedAt: "—",
    timezone: "GMT+7 (WIB)",
    location: "Jakarta, Indonesia",
    tags: [member.team || "member", member.generationLabel],
    generationId: member.generationId,
    avatarUrl: member.img,
  };
}
